-- Swarm-OS Telemetry Schema v2
-- Captures the full agent harness: sessions, user queries, AI reasoning,
-- tool calls, tool outputs, build metrics, quality metrics, phase progress.
--
-- Schema v1 (build_metrics, session_metrics, quality_metrics, phase_progress)
-- is preserved unchanged. v2 adds: sessions, user_queries, ai_reasoning,
-- tool_calls, tool_outputs, session_summaries.

-- ============================================================================
-- v1 tables (preserved)
-- ============================================================================

CREATE TABLE IF NOT EXISTS build_metrics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TEXT NOT NULL DEFAULT (datetime('now')),
    compile_time_ms INTEGER,
    test_total INTEGER DEFAULT 0,
    test_passed INTEGER DEFAULT 0,
    test_failed INTEGER DEFAULT 0,
    test_skipped INTEGER DEFAULT 0,
    binary_size_bytes INTEGER,
    coverage_percent REAL,
    lint_errors INTEGER DEFAULT 0,
    stack TEXT CHECK(stack IN ('rust', 'react', 'python', 'all'))
);

CREATE TABLE IF NOT EXISTS session_metrics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL,
    timestamp TEXT NOT NULL DEFAULT (datetime('now')),
    query_count INTEGER DEFAULT 0,
    duration_seconds INTEGER,
    files_changed INTEGER DEFAULT 0,
    lines_added INTEGER DEFAULT 0,
    lines_removed INTEGER DEFAULT 0,
    day_number INTEGER
);

CREATE TABLE IF NOT EXISTS quality_metrics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TEXT NOT NULL DEFAULT (datetime('now')),
    pre_push_failures INTEGER DEFAULT 0,
    regression_count INTEGER DEFAULT 0,
    lint_fixes_applied INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS phase_progress (
    day_number INTEGER PRIMARY KEY,
    status TEXT CHECK(status IN ('planned', 'in_progress', 'completed', 'blocked')) DEFAULT 'planned',
    acceptance_tests_total INTEGER DEFAULT 0,
    acceptance_tests_passing INTEGER DEFAULT 0,
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Initialize Phase 0 days
INSERT OR IGNORE INTO phase_progress (day_number) VALUES
    (1),(2),(3),(4),(5),(6),(7),(8),(9),(10),
    (11),(12),(13),(14),(15),(16),(17),(18),(19),(20);

-- ============================================================================
-- v2 tables — full agent harness telemetry
-- ============================================================================

-- One row per agent session (Claude Code, Cursor, etc.).
-- session_id is a UUID generated by the SessionStart hook.
CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,                       -- UUID v4
    started_at TEXT NOT NULL DEFAULT (datetime('now')),
    ended_at TEXT,
    agent_type TEXT NOT NULL,                  -- 'claude-code', 'cursor', 'aider', 'super-z', 'manual'
    agent_version TEXT,                        -- e.g. 'claude-sonnet-4.6'
    cwd TEXT,                                  -- working directory
    git_branch TEXT,                           -- branch at session start
    git_head_sha TEXT,                         -- HEAD at session start
    query_count INTEGER DEFAULT 0,             -- incremented per user query
    tool_call_count INTEGER DEFAULT 0,         -- incremented per tool call
    files_changed INTEGER DEFAULT 0,           -- from git diff at session end
    lines_added INTEGER DEFAULT 0,
    lines_removed INTEGER DEFAULT 0,
    duration_seconds INTEGER,                  -- set on session end
    exit_reason TEXT                           -- 'normal', 'crash', 'timeout', 'manual'
);

-- Every user prompt submitted during a session.
CREATE TABLE IF NOT EXISTS user_queries (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL REFERENCES sessions(id),
    query_number INTEGER NOT NULL,             -- 1-indexed within session
    timestamp TEXT NOT NULL DEFAULT (datetime('now')),
    prompt TEXT NOT NULL,                      -- full user message
    prompt_tokens_estimate INTEGER,            -- rough token estimate (chars/4)
    response_tokens_estimate INTEGER,           -- rough token estimate of AI response
    response_duration_ms INTEGER,              -- wall-clock from query to response-complete
    tool_calls_invoked INTEGER DEFAULT 0,      -- count of tool calls triggered by this query
    files_modified INTEGER DEFAULT 0,          -- count of files modified in response
    FOREIGN KEY (session_id) REFERENCES sessions(id)
);

-- AI reasoning / thinking traces (chain-of-thought, scratchpad, planning).
-- One query can produce multiple reasoning steps.
CREATE TABLE IF NOT EXISTS ai_reasoning (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL REFERENCES sessions(id),
    query_id INTEGER NOT NULL REFERENCES user_queries(id),
    step_number INTEGER NOT NULL,              -- 1-indexed within query
    timestamp TEXT NOT NULL DEFAULT (datetime('now')),
    reasoning_type TEXT NOT NULL,              -- 'thinking', 'planning', 'reflection', 'decision', 'tool_selection'
    content TEXT NOT NULL,                     -- the reasoning text
    duration_ms INTEGER,                       -- time spent producing this step
    FOREIGN KEY (session_id) REFERENCES sessions(id),
    FOREIGN KEY (query_id) REFERENCES user_queries(id)
);

-- Every tool call made by the AI (Bash, Edit, Write, Read, Grep, etc.).
CREATE TABLE IF NOT EXISTS tool_calls (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL REFERENCES sessions(id),
    query_id INTEGER NOT NULL REFERENCES user_queries(id),
    call_number INTEGER NOT NULL,              -- 1-indexed within session
    timestamp TEXT NOT NULL DEFAULT (datetime('now')),
    tool_name TEXT NOT NULL,                   -- 'Bash', 'Edit', 'Write', 'Read', 'Grep', 'Glob', 'Task', etc.
    tool_input TEXT,                           -- JSON-serialized input args
    duration_ms INTEGER,                       -- wall-clock execution time
    success INTEGER NOT NULL DEFAULT 1,        -- 1=success, 0=failure
    error_message TEXT,                        -- populated on failure
    FOREIGN KEY (session_id) REFERENCES sessions(id),
    FOREIGN KEY (query_id) REFERENCES user_queries(id)
);

-- Output/result of each tool call. Stored separately because outputs can be large.
CREATE TABLE IF NOT EXISTS tool_outputs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tool_call_id INTEGER NOT NULL REFERENCES tool_calls(id),
    output_type TEXT NOT NULL,                 -- 'stdout', 'stderr', 'result', 'file_content', 'error'
    content TEXT NOT NULL,                     -- the actual output text
    content_length INTEGER NOT NULL,           -- bytes
    truncated INTEGER DEFAULT 0,               -- 1 if content was truncated for storage
    FOREIGN KEY (tool_call_id) REFERENCES tool_calls(id)
);

-- Session-end summary written by the Stop hook.
CREATE TABLE IF NOT EXISTS session_summaries (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL REFERENCES sessions(id),
    timestamp TEXT NOT NULL DEFAULT (datetime('now')),
    summary TEXT NOT NULL,                     -- AI-generated or hook-generated summary
    tasks_completed INTEGER DEFAULT 0,
    tasks_failed INTEGER DEFAULT 0,
    tests_run INTEGER DEFAULT 0,
    tests_passed INTEGER DEFAULT 0,
    commits_made INTEGER DEFAULT 0,
    UNIQUE(session_id)
);

-- ============================================================================
-- Indexes for query performance
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_sessions_started_at ON sessions(started_at);
CREATE INDEX IF NOT EXISTS idx_sessions_agent_type ON sessions(agent_type);
CREATE INDEX IF NOT EXISTS idx_user_queries_session_id ON user_queries(session_id);
CREATE INDEX IF NOT EXISTS idx_user_queries_timestamp ON user_queries(timestamp);
CREATE INDEX IF NOT EXISTS idx_ai_reasoning_session_id ON ai_reasoning(session_id);
CREATE INDEX IF NOT EXISTS idx_ai_reasoning_query_id ON ai_reasoning(query_id);
CREATE INDEX IF NOT EXISTS idx_tool_calls_session_id ON tool_calls(session_id);
CREATE INDEX IF NOT EXISTS idx_tool_calls_query_id ON tool_calls(query_id);
CREATE INDEX IF NOT EXISTS idx_tool_calls_tool_name ON tool_calls(tool_name);
CREATE INDEX IF NOT EXISTS idx_tool_calls_timestamp ON tool_calls(timestamp);
CREATE INDEX IF NOT EXISTS idx_tool_outputs_tool_call_id ON tool_outputs(tool_call_id);

-- ============================================================================
-- Schema version tracking
-- ============================================================================

CREATE TABLE IF NOT EXISTS schema_meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('schema_version', '2');
INSERT OR REPLACE INTO schema_meta (key, value) VALUES ('schema_version_updated_at', datetime('now'));
